//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Web.ServicoPromocao {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Promocao", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Promocao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        private double ValorField;
        
        private int TipoDescontoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SW.Web.ServicoPromocao.TipoDesconto TipoDescontoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int TipoDescontoId {
            get {
                return this.TipoDescontoIdField;
            }
            set {
                if ((this.TipoDescontoIdField.Equals(value) != true)) {
                    this.TipoDescontoIdField = value;
                    this.RaisePropertyChanged("TipoDescontoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public SW.Web.ServicoPromocao.TipoDesconto TipoDesconto {
            get {
                return this.TipoDescontoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDescontoField, value) != true)) {
                    this.TipoDescontoField = value;
                    this.RaisePropertyChanged("TipoDesconto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoDesconto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TipoDesconto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescontoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Desconto {
            get {
                return this.DescontoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescontoField, value) != true)) {
                    this.DescontoField = value;
                    this.RaisePropertyChanged("Desconto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoPromocao.PromocaoSoap")]
    public interface PromocaoSoap {
        
        // CODEGEN: Generating message contract since element name ListarResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        SW.Web.ServicoPromocao.ListarResponse Listar(SW.Web.ServicoPromocao.ListarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<SW.Web.ServicoPromocao.ListarResponse> ListarAsync(SW.Web.ServicoPromocao.ListarRequest request);
        
        // CODEGEN: Generating message contract since element name ListarPorIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarPorId", ReplyAction="*")]
        SW.Web.ServicoPromocao.ListarPorIdResponse ListarPorId(SW.Web.ServicoPromocao.ListarPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarPorId", ReplyAction="*")]
        System.Threading.Tasks.Task<SW.Web.ServicoPromocao.ListarPorIdResponse> ListarPorIdAsync(SW.Web.ServicoPromocao.ListarPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Excluir", ReplyAction="*")]
        void Excluir(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Excluir", ReplyAction="*")]
        System.Threading.Tasks.Task ExcluirAsync(int id);
        
        // CODEGEN: Generating message contract since element name promocao from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cadastrar", ReplyAction="*")]
        SW.Web.ServicoPromocao.CadastrarResponse Cadastrar(SW.Web.ServicoPromocao.CadastrarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cadastrar", ReplyAction="*")]
        System.Threading.Tasks.Task<SW.Web.ServicoPromocao.CadastrarResponse> CadastrarAsync(SW.Web.ServicoPromocao.CadastrarRequest request);
        
        // CODEGEN: Generating message contract since element name promocao from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Atualizar", ReplyAction="*")]
        SW.Web.ServicoPromocao.AtualizarResponse Atualizar(SW.Web.ServicoPromocao.AtualizarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Atualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<SW.Web.ServicoPromocao.AtualizarResponse> AtualizarAsync(SW.Web.ServicoPromocao.AtualizarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Listar", Namespace="http://tempuri.org/", Order=0)]
        public SW.Web.ServicoPromocao.ListarRequestBody Body;
        
        public ListarRequest() {
        }
        
        public ListarRequest(SW.Web.ServicoPromocao.ListarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListarRequestBody {
        
        public ListarRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarResponse", Namespace="http://tempuri.org/", Order=0)]
        public SW.Web.ServicoPromocao.ListarResponseBody Body;
        
        public ListarResponse() {
        }
        
        public ListarResponse(SW.Web.ServicoPromocao.ListarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SW.Web.ServicoPromocao.Promocao[] ListarResult;
        
        public ListarResponseBody() {
        }
        
        public ListarResponseBody(SW.Web.ServicoPromocao.Promocao[] ListarResult) {
            this.ListarResult = ListarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarPorId", Namespace="http://tempuri.org/", Order=0)]
        public SW.Web.ServicoPromocao.ListarPorIdRequestBody Body;
        
        public ListarPorIdRequest() {
        }
        
        public ListarPorIdRequest(SW.Web.ServicoPromocao.ListarPorIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarPorIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public ListarPorIdRequestBody() {
        }
        
        public ListarPorIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarPorIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public SW.Web.ServicoPromocao.ListarPorIdResponseBody Body;
        
        public ListarPorIdResponse() {
        }
        
        public ListarPorIdResponse(SW.Web.ServicoPromocao.ListarPorIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarPorIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SW.Web.ServicoPromocao.Promocao ListarPorIdResult;
        
        public ListarPorIdResponseBody() {
        }
        
        public ListarPorIdResponseBody(SW.Web.ServicoPromocao.Promocao ListarPorIdResult) {
            this.ListarPorIdResult = ListarPorIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CadastrarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Cadastrar", Namespace="http://tempuri.org/", Order=0)]
        public SW.Web.ServicoPromocao.CadastrarRequestBody Body;
        
        public CadastrarRequest() {
        }
        
        public CadastrarRequest(SW.Web.ServicoPromocao.CadastrarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CadastrarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SW.Web.ServicoPromocao.Promocao promocao;
        
        public CadastrarRequestBody() {
        }
        
        public CadastrarRequestBody(SW.Web.ServicoPromocao.Promocao promocao) {
            this.promocao = promocao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CadastrarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CadastrarResponse", Namespace="http://tempuri.org/", Order=0)]
        public SW.Web.ServicoPromocao.CadastrarResponseBody Body;
        
        public CadastrarResponse() {
        }
        
        public CadastrarResponse(SW.Web.ServicoPromocao.CadastrarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CadastrarResponseBody {
        
        public CadastrarResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AtualizarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Atualizar", Namespace="http://tempuri.org/", Order=0)]
        public SW.Web.ServicoPromocao.AtualizarRequestBody Body;
        
        public AtualizarRequest() {
        }
        
        public AtualizarRequest(SW.Web.ServicoPromocao.AtualizarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AtualizarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SW.Web.ServicoPromocao.Promocao promocao;
        
        public AtualizarRequestBody() {
        }
        
        public AtualizarRequestBody(SW.Web.ServicoPromocao.Promocao promocao) {
            this.promocao = promocao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AtualizarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AtualizarResponse", Namespace="http://tempuri.org/", Order=0)]
        public SW.Web.ServicoPromocao.AtualizarResponseBody Body;
        
        public AtualizarResponse() {
        }
        
        public AtualizarResponse(SW.Web.ServicoPromocao.AtualizarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AtualizarResponseBody {
        
        public AtualizarResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PromocaoSoapChannel : SW.Web.ServicoPromocao.PromocaoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PromocaoSoapClient : System.ServiceModel.ClientBase<SW.Web.ServicoPromocao.PromocaoSoap>, SW.Web.ServicoPromocao.PromocaoSoap {
        
        public PromocaoSoapClient() {
        }
        
        public PromocaoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PromocaoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PromocaoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PromocaoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SW.Web.ServicoPromocao.ListarResponse SW.Web.ServicoPromocao.PromocaoSoap.Listar(SW.Web.ServicoPromocao.ListarRequest request) {
            return base.Channel.Listar(request);
        }
        
        public SW.Web.ServicoPromocao.Promocao[] Listar() {
            SW.Web.ServicoPromocao.ListarRequest inValue = new SW.Web.ServicoPromocao.ListarRequest();
            inValue.Body = new SW.Web.ServicoPromocao.ListarRequestBody();
            SW.Web.ServicoPromocao.ListarResponse retVal = ((SW.Web.ServicoPromocao.PromocaoSoap)(this)).Listar(inValue);
            return retVal.Body.ListarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SW.Web.ServicoPromocao.ListarResponse> SW.Web.ServicoPromocao.PromocaoSoap.ListarAsync(SW.Web.ServicoPromocao.ListarRequest request) {
            return base.Channel.ListarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SW.Web.ServicoPromocao.ListarResponse> ListarAsync() {
            SW.Web.ServicoPromocao.ListarRequest inValue = new SW.Web.ServicoPromocao.ListarRequest();
            inValue.Body = new SW.Web.ServicoPromocao.ListarRequestBody();
            return ((SW.Web.ServicoPromocao.PromocaoSoap)(this)).ListarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SW.Web.ServicoPromocao.ListarPorIdResponse SW.Web.ServicoPromocao.PromocaoSoap.ListarPorId(SW.Web.ServicoPromocao.ListarPorIdRequest request) {
            return base.Channel.ListarPorId(request);
        }
        
        public SW.Web.ServicoPromocao.Promocao ListarPorId(int id) {
            SW.Web.ServicoPromocao.ListarPorIdRequest inValue = new SW.Web.ServicoPromocao.ListarPorIdRequest();
            inValue.Body = new SW.Web.ServicoPromocao.ListarPorIdRequestBody();
            inValue.Body.id = id;
            SW.Web.ServicoPromocao.ListarPorIdResponse retVal = ((SW.Web.ServicoPromocao.PromocaoSoap)(this)).ListarPorId(inValue);
            return retVal.Body.ListarPorIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SW.Web.ServicoPromocao.ListarPorIdResponse> SW.Web.ServicoPromocao.PromocaoSoap.ListarPorIdAsync(SW.Web.ServicoPromocao.ListarPorIdRequest request) {
            return base.Channel.ListarPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SW.Web.ServicoPromocao.ListarPorIdResponse> ListarPorIdAsync(int id) {
            SW.Web.ServicoPromocao.ListarPorIdRequest inValue = new SW.Web.ServicoPromocao.ListarPorIdRequest();
            inValue.Body = new SW.Web.ServicoPromocao.ListarPorIdRequestBody();
            inValue.Body.id = id;
            return ((SW.Web.ServicoPromocao.PromocaoSoap)(this)).ListarPorIdAsync(inValue);
        }
        
        public void Excluir(int id) {
            base.Channel.Excluir(id);
        }
        
        public System.Threading.Tasks.Task ExcluirAsync(int id) {
            return base.Channel.ExcluirAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SW.Web.ServicoPromocao.CadastrarResponse SW.Web.ServicoPromocao.PromocaoSoap.Cadastrar(SW.Web.ServicoPromocao.CadastrarRequest request) {
            return base.Channel.Cadastrar(request);
        }
        
        public void Cadastrar(SW.Web.ServicoPromocao.Promocao promocao) {
            SW.Web.ServicoPromocao.CadastrarRequest inValue = new SW.Web.ServicoPromocao.CadastrarRequest();
            inValue.Body = new SW.Web.ServicoPromocao.CadastrarRequestBody();
            inValue.Body.promocao = promocao;
            SW.Web.ServicoPromocao.CadastrarResponse retVal = ((SW.Web.ServicoPromocao.PromocaoSoap)(this)).Cadastrar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SW.Web.ServicoPromocao.CadastrarResponse> SW.Web.ServicoPromocao.PromocaoSoap.CadastrarAsync(SW.Web.ServicoPromocao.CadastrarRequest request) {
            return base.Channel.CadastrarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SW.Web.ServicoPromocao.CadastrarResponse> CadastrarAsync(SW.Web.ServicoPromocao.Promocao promocao) {
            SW.Web.ServicoPromocao.CadastrarRequest inValue = new SW.Web.ServicoPromocao.CadastrarRequest();
            inValue.Body = new SW.Web.ServicoPromocao.CadastrarRequestBody();
            inValue.Body.promocao = promocao;
            return ((SW.Web.ServicoPromocao.PromocaoSoap)(this)).CadastrarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SW.Web.ServicoPromocao.AtualizarResponse SW.Web.ServicoPromocao.PromocaoSoap.Atualizar(SW.Web.ServicoPromocao.AtualizarRequest request) {
            return base.Channel.Atualizar(request);
        }
        
        public void Atualizar(SW.Web.ServicoPromocao.Promocao promocao) {
            SW.Web.ServicoPromocao.AtualizarRequest inValue = new SW.Web.ServicoPromocao.AtualizarRequest();
            inValue.Body = new SW.Web.ServicoPromocao.AtualizarRequestBody();
            inValue.Body.promocao = promocao;
            SW.Web.ServicoPromocao.AtualizarResponse retVal = ((SW.Web.ServicoPromocao.PromocaoSoap)(this)).Atualizar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SW.Web.ServicoPromocao.AtualizarResponse> SW.Web.ServicoPromocao.PromocaoSoap.AtualizarAsync(SW.Web.ServicoPromocao.AtualizarRequest request) {
            return base.Channel.AtualizarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SW.Web.ServicoPromocao.AtualizarResponse> AtualizarAsync(SW.Web.ServicoPromocao.Promocao promocao) {
            SW.Web.ServicoPromocao.AtualizarRequest inValue = new SW.Web.ServicoPromocao.AtualizarRequest();
            inValue.Body = new SW.Web.ServicoPromocao.AtualizarRequestBody();
            inValue.Body.promocao = promocao;
            return ((SW.Web.ServicoPromocao.PromocaoSoap)(this)).AtualizarAsync(inValue);
        }
    }
}
